export const TASK_RECT_WIDTH = 200;
export const TASK_RECT_HEIGHT = 100;
export const TASK_RECT_HEIGHT_HALF = TASK_RECT_HEIGHT / 2;
export const TASK_HANDLE_SIZE = 8;
export const TASK_HANDLE_SIZE_HALF = TASK_HANDLE_SIZE / 2;
export const TASK_HANDLE_Y_SHIFT = TASK_RECT_HEIGHT_HALF - TASK_HANDLE_SIZE_HALF;
